# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impact_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgImp(object):
    def setupUi(self, dlgImp):
        dlgImp.setObjectName("dlgImp")
        dlgImp.resize(419, 343)
        self.tblImpacts = QtWidgets.QTableWidget(dlgImp)
        self.tblImpacts.setGeometry(QtCore.QRect(10, 10, 401, 321))
        self.tblImpacts.setAlternatingRowColors(True)
        self.tblImpacts.setObjectName("tblImpacts")
        self.tblImpacts.setColumnCount(3)
        self.tblImpacts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblImpacts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblImpacts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblImpacts.setHorizontalHeaderItem(2, item)

        self.retranslateUi(dlgImp)
        QtCore.QMetaObject.connectSlotsByName(dlgImp)

    def retranslateUi(self, dlgImp):
        _translate = QtCore.QCoreApplication.translate
        dlgImp.setWindowTitle(_translate("dlgImp", "Tabla de Impactos"))
        item = self.tblImpacts.horizontalHeaderItem(0)
        item.setText(_translate("dlgImp", "Proyecto"))
        item = self.tblImpacts.horizontalHeaderItem(1)
        item.setText(_translate("dlgImp", "Tipo"))
        item = self.tblImpacts.horizontalHeaderItem(2)
        item.setText(_translate("dlgImp", "Distancia"))
